CODE_OF_CONDUCT.md is added, based on other repositories of fluxcd
fluxcd/community pull request #14
Opened 2020-10-10 08:29 UTC by selinsezi

Fixes #4 
Adds CODE_OF_CONDUCT.md

2020-10-11 17:53 UTC, scottrigby requested changes

2020-10-11 17:53 UTC, scottrigby commented on CODE_OF_CONDUCT.md
> +CNCF events are governed by the Linux Foundation [Code of Conduct](https://events.linuxfoundation.org/code-of-conduct/) available on the event page. This is designed to be compatible with the above p
This file should point to the CNCF CoC, not copy it.

See:
- https://github.com/fluxcd/flux/blob/master/CODE_OF_CONDUCT.md
- https://github.com/fluxcd/toolkit/blob/main/CODE_OF_CONDUCT.md
- https://github.com/fluxcd/helm-controller/blob/main/CODE_OF_CONDUCT.md

And other CNCF projects:
- https://github.com/kubernetes/community/blob/master/code-of-conduct.md
- https://github.com/helm/community/blob/master/code-of-conduct.md


Essentially, this:
```suggestion
# Community Code of Conduct

Flux follows the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).
```

2020-10-19 13:46 UTC, hiddeco reviewed
Thanks for making the change as requested! It would be awesome if you could [limit your commit message to a maximum of 50 characters](https://chris.beams.io/posts/git-commit/#seven-rules).

For example:

```
Add `CODE_OF_CONDUCT.md`

Based on other repositories of CNCF projects.
```

2020-10-19 13:46 UTC, hiddeco commented on CODE_OF_CONDUCT.md
> +
```suggestion

```

(There should only be _one_ trailing white line)

2020-10-22 18:34 UTC, scottrigby requested changes

2020-10-22 18:34 UTC, scottrigby commented on CODE_OF_CONDUCT.md
> +## Flux Community Code of Conduct## Flux Community Code of Conduct
This should not repeat. And should be a H1 (even if if some other Flux repo have as a H2. Those should probably be changed as well).
```suggestion
# Flux Community Code of Conduct
```

2020-10-22 18:35 UTC, scottrigby commented
@selinsezi Also I'm not sure if you're aware of the ability to commit review suggestions directly in GitHub. If not, check this out: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes

2020-10-27 15:08 UTC, dholbach commented
Thanks for your work on this. I merged #20 instead, so I'll close this now.

2020-10-27 15:08 UTC, closed without merging